# Generated by Django 3.2 on 2021-12-14 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proposal_job_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sector_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='job_proposal',
            name='lib_contract',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AlterField(
            model_name='job_proposal',
            name='city_region',
            field=models.CharField(max_length=200, verbose_name='Ville / Region '),
        ),
        migrations.AddField(
            model_name='job_proposal',
            name='sector_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='proposal_job_management.sector_type'),
        ),
    ]
