# Generated by Django 3.2 on 2021-12-14 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal_job_management', '0002_auto_20211214_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_proposal',
            name='enterprise_activity',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='job_proposal',
            name='enterprise_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='job_proposal',
            name='job_description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='job_proposal',
            name='profile_searched',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='job_proposal',
            name='urgent',
            field=models.BooleanField(default=False),
        ),
    ]
