# Generated by Django 3.2 on 2021-12-15 04:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal_job_management', '0003_auto_20211214_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_proposal',
            name='proposal_expired_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 15, 4, 48, 47, 386049)),
        ),
    ]
