# Generated by Django 3.2 on 2021-12-26 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposal_job_management', '0005_auto_20211215_0452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job_proposal',
            name='proposal_expired_date',
        ),
    ]
