# Generated by Django 3.2 on 2021-12-26 18:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('proposal_job_management', '0006_remove_job_proposal_proposal_expired_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_proposal',
            name='proposal_expired_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 26, 18, 6, 11, 613374, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
