# Generated by Django 3.2 on 2021-12-26 18:27

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proposal_job_management', '0008_formation_proposal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portal_client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('adress', models.CharField(max_length=200)),
                ('nif_stat', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='formation_proposal',
            name='enterprise',
            field=models.CharField(default=datetime.datetime(2021, 12, 26, 18, 27, 51, 33684, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='formation_proposal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='formation_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Add_portal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('portal_client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='add_client', to='proposal_job_management.portal_client')),
            ],
        ),
    ]
