# Generated by Django 3.2 on 2021-12-26 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposal_job_management', '0009_auto_20211226_1827'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Add_portal',
        ),
        migrations.DeleteModel(
            name='Portal_client',
        ),
    ]
