# Generated by Django 3.2 on 2022-01-01 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposal_job_management', '0010_auto_20211226_1840'),
    ]

    operations = [
        migrations.DeleteModel(
            name='formation_proposal',
        ),
    ]
