# Generated by Django 3.2 on 2022-01-10 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_is_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_employee',
            new_name='is_employer',
        ),
    ]
